# Generated by Django 4.0.3 on 2022-06-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_app_per_jesse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csvbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.FileField(upload_to='')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
