# Generated by Django 4.0.3 on 2022-06-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_book_delete_csvbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csvforheat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.FileField(upload_to='')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
