# Generated by Django 4.0.3 on 2022-06-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_csvforheat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csvforheatcombi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterModelOptions(
            name='csvforheat',
            options={},
        ),
    ]
