# Generated by Django 3.2.14 on 2022-07-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_book_delete_csv_delete_csvforheatcombi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csvfor_bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Csvfor_heat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.FileField(upload_to='')),
            ],
        ),
    ]
