# Generated by Django 4.0.5 on 2022-07-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_user_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('reason', models.TextField(max_length=500)),
                ('block_no', models.IntegerField()),
            ],
        ),
    ]
