# Generated by Django 4.0.5 on 2022-08-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_user_name_user_details_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='block_no',
            field=models.CharField(max_length=500),
        ),
    ]
