# Generated by Django 4.0.5 on 2022-08-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_user_details_block_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='battery_current',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='battery_voltage',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='cut_off_thresold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='text',
            name='no_of_operational',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
