# Generated by Django 4.0.5 on 2022-08-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_text_battery_current_text_battery_voltage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='battery_current',
            field=models.CharField(default=0, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='battery_voltage',
            field=models.CharField(default=0, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='no_of_operational',
            field=models.CharField(default=0, max_length=60, null=True),
        ),
    ]
