# Generated by Django 4.0.5 on 2022-08-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_text_battery_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='remove_first_col',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='text',
            name='cut_off_thresold',
            field=models.CharField(default=0, max_length=60, null=True),
        ),
    ]
