# Generated by Django 4.0.5 on 2022-08-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_text_remove_first_col_alter_text_cut_off_thresold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='remove_first_col',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
