# Generated by Django 3.2.15 on 2022-09-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_text_remove_first_col'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='remove_first_col',
            field=models.CharField(default=0, max_length=60, null=True),
        ),
    ]
