# Generated by Django 3.2.15 on 2022-09-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_text_remove_first_col'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csv_score_downld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.FileField(upload_to='')),
            ],
        ),
    ]
