# Generated by Django 3.2.15 on 2022-10-11 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_csv_for_heat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Csvfor_bar',
        ),
        migrations.DeleteModel(
            name='Csvforheat',
        ),
    ]
