# Generated by Django 3.2.15 on 2022-10-11 04:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0028_auto_20221011_0940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='App_per_jesse',
            new_name='Permissions',
        ),
    ]
