# Generated by Django 3.2.15 on 2022-10-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_text_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='optionselected',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('optionsel', models.FileField(upload_to='')),
            ],
        ),
    ]
