# Generated by Django 3.2.15 on 2022-11-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_optionselected_optionsel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='optionselected',
        ),
        migrations.RemoveField(
            model_name='text',
            name='battery_current',
        ),
        migrations.RemoveField(
            model_name='text',
            name='battery_voltage',
        ),
        migrations.AddField(
            model_name='text',
            name='empty_columns',
            field=models.CharField(default=0, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='remove_static',
            field=models.CharField(default=0, max_length=60, null=True),
        ),
    ]
