# Generated by Django 3.2.15 on 2022-11-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20221121_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='empty_columns',
            field=models.CharField(default='NO', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='remove_first_col',
            field=models.CharField(default='NO', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='remove_static',
            field=models.CharField(default='NO', max_length=60, null=True),
        ),
    ]
