# Generated by Django 3.2.15 on 2022-11-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20221121_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='empty_columns',
        ),
        migrations.RemoveField(
            model_name='text',
            name='remove_static',
        ),
    ]
