# Generated by Django 3.2.15 on 2022-11-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20221123_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='inject_anamolies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('all', models.CharField(default=0, max_length=60, null=True)),
                ('point_anomalies', models.CharField(default=0, max_length=60, null=True)),
                ('fluctuating', models.CharField(default=0, max_length=60, null=True)),
                ('bias', models.CharField(default=0, max_length=60, null=True)),
                ('dead', models.CharField(default=0, max_length=60, null=True)),
                ('cer', models.CharField(default=0, max_length=60, null=True)),
                ('cer_and_slope', models.CharField(default=0, max_length=60, null=True)),
                ('dtw', models.CharField(default=0, max_length=60, null=True)),
            ],
        ),
    ]
