# Generated by Django 3.2.15 on 2022-12-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_text_cut_off_thresold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='no_of_operational',
        ),
        migrations.AddField(
            model_name='text',
            name='cut_off_thresold',
            field=models.CharField(default=0, max_length=60, null=True),
        ),
    ]
