# Generated by Django 4.0.3 on 2022-07-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_two', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='csv',
            field=models.FileField(default=None, null=True, upload_to='newz/'),
        ),
    ]
