# Generated by Django 4.0.3 on 2022-07-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_two', '0002_alter_csv_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='csv',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
